import mongoose from 'mongoose';
import dotenv from 'dotenv';
import { Case } from '../models/Case';
import { Report } from '../models/Report';
import { Match } from '../models/Match';
import { Verification } from '../models/Verification';
import { AuditLog } from '../models/AuditLog';
import { SourceFeed } from '../models/SourceFeed';

dotenv.config();

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb+srv://kartiksinghal28032006_db_user:5gRBOdtnpfDg7yyS@cluster0.pdqrenn.mongodb.net/reconnect_network?retryWrites=true&w=majority&appName=Cluster0';

const seedData = async () => {
  try {
    console.log('[Seed] Connecting to MongoDB Atlas...');
    await mongoose.connect(MONGODB_URI);
    console.log('[Seed] Connected successfully.');

    // 1. Clear existing collections
    console.log('[Seed] Resetting collections for fresh live data...');
    await Promise.all([
      Case.deleteMany({}),
      Report.deleteMany({}),
      Match.deleteMany({}),
      Verification.deleteMany({}),
      AuditLog.deleteMany({}),
      SourceFeed.deleteMany({}),
    ]);

    // 2. Insert 12 Comprehensive Cases
    console.log('[Seed] Seeding live Cases...');
    await Case.insertMany([
      {
        caseId: 'MP-2026-00421',
        name: 'Rahul Agrawal',
        aliases: ['Rahul Agarwal', 'R. Agrawal'],
        age: 24,
        gender: 'M',
        lastSeenLocation: 'Relief Zone B (Sector 4 Narmada Riverfront)',
        sector: 'Sector B-4',
        reportedAgo: '9h ago',
        source: 'Helpline 1070',
        priority: 'HIGH',
        status: 'LOOKING FOR A MATCH',
        hasPhoto: true,
        photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80',
        keyMarks: 'Healed scar on right chin (~2cm), small mole below left eye',
        clothing: 'Dark navy blue polo shirt, khaki/beige pants, no footwear',
        height: '176 cm',
        build: 'Slim / Athletic',
        reporterContact: '+91 98260 11984 (Brother: Sumeet Agrawal)',
        duplicatesMerged: false,
        canonicalId: 'MP-2026-00421',
        timeline: [
          { step: 1, title: 'Case Intake & Profile Registration', timestamp: '11 Sep 2026, 06:40 LOC', completed: true, description: 'Missing person intake filed via State Helpline 1070 by brother Sumeet Agrawal.' },
          { step: 2, title: 'Multi-Source Correlation Scan', timestamp: '11 Sep 2026, 07:15 LOC', completed: true, description: 'Continuous automated biometrics and physical attribute scan across 6 active camps.' },
          { step: 3, title: 'High-Confidence Field Candidate Flagged', timestamp: '11 Sep 2026, 14:22 LOC', completed: false, current: true, description: 'Matching candidate FND-2026-01892 at Ward 6 Relief Camp (94% confidence).' },
          { step: 4, title: 'Sworn Physical Verification & Reunion', timestamp: 'Pending Verification', completed: false, description: 'On-site dispatcher biometric confirmation and family notification dispatch.' },
        ],
      },
      {
        caseId: 'MP-2026-00388',
        name: 'Ananya Sharma',
        aliases: ['Chhoti'],
        age: 4,
        gender: 'F',
        lastSeenLocation: 'Hoshangabad Bus Stand Triage Point',
        sector: 'Sector A-1',
        reportedAgo: '2h 15m ago',
        source: 'Citizen Tip (Smt. Rekha)',
        priority: 'CRITICAL',
        status: 'AWAITING VERIFICATION',
        isMinor: true,
        hasPhoto: true,
        photoUrl: 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?w=400&q=80',
        keyMarks: 'Red hair ribbon, small birthmark on left elbow, floral frock',
        clothing: 'Yellow floral dress, red hair ribbon',
        canonicalId: 'MP-2026-00388',
      },
      {
        caseId: 'MP-2026-00392',
        name: 'Ramesh Chandra Verma',
        aliases: ['R.C. Verma'],
        age: 58,
        gender: 'M',
        lastSeenLocation: 'Sethani Ghat Evacuation Point',
        sector: 'Sector B-2',
        reportedAgo: '4h ago',
        source: 'District Hospital Ward 3',
        priority: 'CRITICAL',
        status: 'AWAITING VERIFICATION',
        hasPhoto: true,
        keyMarks: 'Healed scar on left forearm, spectacles',
        clothing: 'White kurta pyjama',
        canonicalId: 'MP-2026-00392',
      },
      {
        caseId: 'MP-2026-00395',
        name: 'Sunita Devi Ahirwar',
        aliases: [],
        age: 34,
        gender: 'F',
        lastSeenLocation: 'Vidisha Relief Camp #2',
        sector: 'Sector C-3',
        reportedAgo: '6h ago',
        source: 'Red Cross Field Team B',
        priority: 'HIGH',
        status: 'LOOKING FOR A MATCH',
        hasPhoto: true,
        keyMarks: 'Green printed saree, silver payal anklet',
        clothing: 'Green printed saree',
        canonicalId: 'MP-2026-00395',
      },
      {
        caseId: 'MP-2026-00399',
        name: 'Aarav Sharma',
        aliases: ['Guddu'],
        age: 8,
        gender: 'M',
        lastSeenLocation: 'Sehore Govt High School Shelter',
        sector: 'Sector S-1',
        reportedAgo: '7h ago',
        source: 'Childline 1098 Ingest',
        priority: 'CRITICAL',
        status: 'AWAITING VERIFICATION',
        isMinor: true,
        hasPhoto: true,
        keyMarks: 'Yellow cartoon print t-shirt, oval birthmark on right shoulder',
        clothing: 'Yellow cartoon t-shirt, blue shorts',
        canonicalId: 'MP-2026-00399',
      },
      {
        caseId: 'MP-2026-00405',
        name: 'Mohammad Farooq Siddiqui',
        aliases: ['Farooq Bhai'],
        age: 62,
        gender: 'M',
        lastSeenLocation: 'Narmada Valley Rescue Sector 9',
        sector: 'Sector B-9',
        reportedAgo: '11h ago',
        source: 'NDRF Rescue Log #042',
        priority: 'HIGH',
        status: 'LOOKING FOR A MATCH',
        hasPhoto: true,
        keyMarks: 'Grey beard, walked with limp, silver wristwatch',
        clothing: 'Grey kurta, brown jacket',
        canonicalId: 'MP-2026-00405',
      },
      {
        caseId: 'MP-2026-00412',
        name: 'Pooja Vishwakarma',
        aliases: [],
        age: 19,
        gender: 'F',
        lastSeenLocation: 'Pipariya Relief Junction',
        sector: 'Sector P-2',
        reportedAgo: '12h ago',
        source: 'Public Web Portal',
        priority: 'ROUTINE',
        status: 'LOOKING FOR A MATCH',
        hasPhoto: false,
        keyMarks: 'Blue dupatta, black spectacles',
        clothing: 'Blue salwar kameez',
        canonicalId: 'MP-2026-00412',
      },
      {
        caseId: 'MP-2026-00418',
        name: 'Deepak Kumar Soni',
        aliases: ['Deepu'],
        age: 28,
        gender: 'M',
        lastSeenLocation: 'Sector 4 Riverfront Embankment',
        sector: 'Sector B-4',
        reportedAgo: '13h ago',
        source: 'Helpline 1070',
        priority: 'CRITICAL',
        status: 'LOOKING FOR A MATCH',
        hasPhoto: true,
        keyMarks: 'Tattoo of trident on right arm',
        clothing: 'Red t-shirt, blue jeans',
        canonicalId: 'MP-2026-00418',
      },
      {
        caseId: 'MP-2026-00424',
        name: 'Kavita Yadav',
        aliases: [],
        age: 31,
        gender: 'F',
        lastSeenLocation: 'Hoshangabad Ghat Sector 3',
        sector: 'Sector B-3',
        reportedAgo: '14h ago',
        source: 'SDRF Camp Desk',
        priority: 'HIGH',
        status: 'VERIFIED MATCH',
        hasPhoto: true,
        keyMarks: 'Gold nose pin, floral saree',
        clothing: 'Red floral saree',
        canonicalId: 'MP-2026-00424',
        verifiedCandidate: {
          id: 'FND-2026-01740',
          name: 'Kavita Yadav',
          ref: 'FND-2026-01740',
          confidence: 97,
          location: 'Sector 3 Medical Center',
          distance: '1.2 km',
          evidence: 'Verified via SDRF registration ID and family phone match.',
          verifiedBy: 'DISP-412 (Field Dispatcher)',
          verifiedAt: '11 Sep 2026, 11:30 LOC',
          notes: 'Family safely reunited at camp.',
        },
      },
      {
        caseId: 'MP-2026-00429',
        name: 'Vikram Solanki',
        aliases: ['Vicky'],
        age: 31,
        gender: 'M',
        lastSeenLocation: 'Budhni Railway Outflow',
        sector: 'Sector A-2 Intake',
        reportedAgo: '15h ago',
        source: 'Helpline 1070',
        priority: 'CRITICAL',
        status: 'LOOKING FOR A MATCH',
        hasPhoto: false,
        keyMarks: 'Tattoo on left wrist',
        clothing: 'Black athletic t-shirt',
        canonicalId: 'MP-2026-00429',
      },
      {
        caseId: 'MP-2026-00432',
        name: 'Meera Bai Choudhary',
        aliases: [],
        age: 65,
        gender: 'F',
        lastSeenLocation: 'Vidisha Relief Camp #1',
        sector: 'Sector C-1',
        reportedAgo: '16h ago',
        source: 'Red Cross Team A',
        priority: 'ROUTINE',
        status: 'FAMILY NOTIFIED',
        hasPhoto: true,
        keyMarks: 'Silver bangles, grey hair tied in bun',
        clothing: 'White cotton saree',
        canonicalId: 'MP-2026-00432',
      },
      {
        caseId: 'MP-2026-00435',
        name: 'Master Rohan Gupta',
        aliases: ['Rohu'],
        age: 6,
        gender: 'M',
        lastSeenLocation: 'Sehore Camp South Entrance',
        sector: 'Sector S-3',
        reportedAgo: '18h ago',
        source: 'Childline 1098',
        priority: 'CRITICAL',
        status: 'VERIFIED MATCH',
        isMinor: true,
        hasPhoto: true,
        keyMarks: 'Birthmark on collarbone',
        clothing: 'Green striped t-shirt, denim shorts',
        canonicalId: 'MP-2026-00435',
      },
    ]);

    // 3. Match Intelligence Candidates
    console.log('[Seed] Seeding Match Intelligence records...');
    await Match.insertMany([
      {
        caseId: 'MP-2026-00421',
        candidateRef: 'FND-2026-01892',
        candidateName: 'Rahul Agarwal',
        location: 'Disaster Relief Camp Ward 6, Polytechnic Campus',
        distance: '3.2 km',
        confidence: 94,
        facialScore: 96,
        demographicScore: 92,
        clothingScore: 90,
        locationScore: 98,
        evidence: 'Facial recognition 96%, age (24), matching right chin scar (~2cm) & navy blue polo shirt confirmed by on-site nurse.',
        status: 'PENDING',
      },
      {
        caseId: 'MP-2026-00421',
        candidateRef: 'HSP-2026-00412',
        candidateName: 'Unidentified Male (Ward 4B)',
        location: 'District Civil Hospital Hoshangabad',
        distance: '7.8 km',
        confidence: 76,
        facialScore: 72,
        demographicScore: 80,
        clothingScore: 75,
        locationScore: 82,
        evidence: 'Age match ~23-26, mild disorientation, matching height and dark hair texture.',
        status: 'PENDING',
      },
      {
        caseId: 'MP-2026-00421',
        candidateRef: 'FND-2026-01740',
        candidateName: 'R. K. Agrawal',
        location: 'Sector 2 Triage Shelter',
        distance: '14.5 km',
        confidence: 58,
        facialScore: 54,
        demographicScore: 65,
        clothingScore: 50,
        locationScore: 62,
        evidence: 'Partial name overlap, age mismatch (reported 31 yrs). Flagged for potential duplicate check.',
        status: 'PENDING',
      },
      {
        caseId: 'MP-2026-00388',
        candidateRef: 'CR-2026-0808',
        candidateName: 'Lost girl with yellow frock',
        location: 'Sehore Govt High School Shelter',
        distance: '4.1 km',
        confidence: 94,
        facialScore: 95,
        demographicScore: 93,
        clothingScore: 96,
        locationScore: 90,
        evidence: 'Yellow floral print frock, red ribbons, age 4, confirmed by Child Protection Volunteer.',
        status: 'PENDING',
      },
      {
        caseId: 'MP-2026-00392',
        candidateRef: 'CR-2026-0811',
        candidateName: 'Disoriented elderly man (Verma Ji)',
        location: 'Sethani Ghat Evacuation Point',
        distance: '0.8 km',
        confidence: 96,
        facialScore: 97,
        demographicScore: 96,
        clothingScore: 94,
        locationScore: 98,
        evidence: 'Superficial laceration, self-identified as Verma Ji, spectacles and white kurta.',
        status: 'PENDING',
      },
    ]);

    // 4. Verification Queue Items
    console.log('[Seed] Seeding Verification Queue...');
    await Verification.insertMany([
      {
        caseId: 'MP-2026-00421',
        name: 'Rahul Agrawal',
        ageGender: '24 M',
        location: 'Relief Zone B (Sector 4 Riverfront)',
        source: 'State Helpline 1070 (Brother: Sumeet)',
        matchTarget: 'Candidate: Rahul Agarwal (Ward 6 Camp)',
        confidence: 94,
        priority: 'HIGH',
        status: 'PHOTO REVIEW',
        reportedAgo: '9h ago',
        assignedOfficer: 'DISP-884 (Certified Dispatcher)',
      },
      {
        caseId: 'RC-CIF-0941',
        name: 'Ramesh Chandra Verma',
        ageGender: '58 M',
        location: 'Hoshangabad Ghat Sector 4',
        source: 'District Civil Hospital Ward 3',
        matchTarget: 'Report #CIF-8812 (Filed by son)',
        confidence: 96,
        priority: 'CRITICAL',
        status: 'PHOTO REVIEW',
        reportedAgo: '12m ago',
        assignedOfficer: 'DISP-412',
      },
      {
        caseId: 'RC-CIF-0938',
        name: 'Sunita Devi Ahirwar',
        ageGender: '34 F',
        location: 'Vidisha Relief Camp #2',
        source: 'Red Cross Field Team B',
        matchTarget: 'Helpline Tip #1070-492',
        confidence: 91,
        priority: 'HIGH',
        status: 'PENDING FIELD CHECK',
        reportedAgo: '24m ago',
        assignedOfficer: 'DISP-609',
      },
      {
        caseId: 'RC-CIF-0935',
        name: 'Aarav Sharma (Minor)',
        ageGender: '8 M',
        location: 'Sehore Govt Shelter',
        source: 'Childline 1098 Field Officer',
        matchTarget: 'Lost Child Case #LC-002',
        confidence: 95,
        priority: 'CRITICAL',
        status: 'BIOMETRIC CORRELATED',
        reportedAgo: '42m ago',
        assignedOfficer: 'DISP-101',
      },
      {
        caseId: 'RC-CIF-0930',
        name: 'Deepak Kumar Soni',
        ageGender: '28 M',
        location: 'Sector 4 Embankment',
        source: 'Helpline 1070',
        matchTarget: 'Triage Intake #TRI-084',
        confidence: 89,
        priority: 'CRITICAL',
        status: 'PENDING FIELD CHECK',
        reportedAgo: '1h 15m ago',
        assignedOfficer: 'DISP-552',
      },
      {
        caseId: 'RC-CIF-0924',
        name: 'Mohammad Farooq Siddiqui',
        ageGender: '62 M',
        location: 'Sector 9 Riverbank',
        source: 'NDRF Search Boat #4',
        matchTarget: 'Intake #NDRF-099',
        confidence: 88,
        priority: 'HIGH',
        status: 'PHOTO REVIEW',
        reportedAgo: '2h ago',
        assignedOfficer: 'DISP-884',
      },
    ]);

    // 5. Community Reports (Citizen Crowdsourcing)
    console.log('[Seed] Seeding Community Reports...');
    await Report.insertMany([
      {
        reportId: 'CR-2026-0814',
        reportType: 'Citizen Tip',
        fullName: 'Anand Prakash Sharma',
        personName: 'Young man in navy blue t-shirt sitting near Sethani temple steps',
        narrativeDescription: 'Saw him sitting on the high temple steps when the boat rescue was loading. He looked exhausted, had a small mark on his chin. Said he was waiting for family from Pipariya.',
        lastKnownLocation: 'Hoshangabad Ghat, Sector 4',
        phoneNumber: '+91 98261 55902',
        address: 'Sethani Mohalla, Ward 12, Hoshangabad',
        clothing: 'Dark navy blue polo shirt, khaki/beige pants, no footwear',
        source: 'Citizen Portal (Mobile Upload)',
        tabCategory: 'New Submissions',
        status: 'NEW',
        isMinor: false,
        possibleMatchingCase: {
          caseId: 'MP-2026-00421',
          person: 'Rahul Agrawal (24 M)',
          confidence: 88,
        },
        duplicateWarning: 'High overlap with SMS tip #TIP-984 received 25m ago describing same temple location.',
      },
      {
        reportId: 'CR-2026-0811',
        reportType: 'Citizen Tip',
        fullName: 'Dr. Reena Saxena (Field Medical Officer)',
        personName: 'Disoriented elderly man brought in by SDRF boat #4',
        narrativeDescription: 'Patient was dehydrated with superficial leg lacerations. Identified himself as Verma Ji from Budhni. Matches physical criteria of family lookup #FL-8831.',
        lastKnownLocation: 'Sethani Ghat Evacuation Point',
        phoneNumber: '+91 94250 88219',
        address: 'District Health Mobile Unit 4',
        clothing: 'White kurta, brown eyeglasses, metallic watch on left wrist',
        source: 'Medical Field Team',
        tabCategory: 'Under Review',
        status: 'UNDER REVIEW',
        isMinor: false,
        possibleMatchingCase: {
          caseId: 'MP-2026-00392',
          person: 'Ramesh Chandra Verma (58 M)',
          confidence: 96,
        },
      },
      {
        reportId: 'CR-2026-0808',
        reportType: 'Citizen Tip',
        fullName: 'Pooja Vishwakarma',
        personName: 'Young girl holding red umbrella near Sehore camp entry',
        narrativeDescription: 'Girl was separated from her aunt during the afternoon food distribution rush. Safely handed over to camp child protection desk.',
        lastKnownLocation: 'Sehore Govt High School Shelter',
        phoneNumber: '+91 97554 33210',
        address: 'Ward 8, Sehore Municipal Camp',
        clothing: 'Yellow floral print frock, red ribbons in braided hair',
        source: 'Citizen Volunteer',
        tabCategory: 'Accepted',
        status: 'ACCEPTED',
        isMinor: true,
        possibleMatchingCase: {
          caseId: 'MP-2026-00388',
          person: 'Ananya Sharma (4 F)',
          confidence: 94,
        },
      },
      {
        reportId: 'CR-2026-0802',
        reportType: 'Citizen Tip',
        fullName: 'Staff Nurse Vandana (Ward 3)',
        personName: 'Female flood rescue victim admitted with minor arm injury',
        narrativeDescription: 'Admitted from rescue boat Sector 8. Mild dehydration, laceration on right arm treated. Able to communicate clearly. Name given as Sunita Ahirwar.',
        lastKnownLocation: 'District Civil Hospital Ward 3',
        phoneNumber: '+91 98263 11099',
        address: 'Civil Hospital Emergency Desk',
        clothing: 'Green saree, red glass bangles',
        source: 'Hospital Emergency Desk',
        tabCategory: 'Accepted',
        status: 'ACCEPTED',
        isMinor: false,
        possibleMatchingCase: {
          caseId: 'RC-CIF-0938',
          person: 'Sunita Devi Ahirwar (34 F)',
          confidence: 96,
        },
      },
      {
        reportId: 'CR-2026-0796',
        reportType: 'Citizen Tip',
        fullName: 'Vikram Joshi (Local Resident)',
        personName: 'Duplicate tip: same sighting of boy at temple reported twice',
        narrativeDescription: 'Saw young man near the temple when water receded 2 inches.',
        lastKnownLocation: 'Sethani Ghat Temple Verandah',
        phoneNumber: '+91 93011 22904',
        address: 'Ghat Road, Hoshangabad',
        clothing: 'Navy blue shirt',
        source: 'Citizen Portal',
        tabCategory: 'Potential Duplicate',
        status: 'DUPLICATE',
        isMinor: false,
        duplicateWarning: 'Exact duplicate of CR-2026-0814 submitted 1 hour later by neighbor.',
      },
    ]);

    // 6. Source Network Feeds
    console.log('[Seed] Seeding Ingest Source Feeds...');
    await SourceFeed.insertMany([
      { source: 'State Helpline 1070', type: 'Emergency Voice / IVR', reportsReceived: 482, verified: 398, pending: 84, lastIngest: '3s ago', status: 'LIVE FEED', sector: 'State Command' },
      { source: 'District Hospitals Network (5 Facilities)', type: 'Direct HL7 / API Bridge', reportsReceived: 312, verified: 284, pending: 28, lastIngest: '45s ago', status: 'LIVE FEED', sector: 'Civil Hospital Network' },
      { source: 'Relief Camp Ward 6 Triage Desk', type: 'Tablet Intake Station', reportsReceived: 215, verified: 189, pending: 26, lastIngest: '2m ago', status: 'LIVE FEED', sector: 'Sector 4 Riverfront' },
      { source: 'Childline 1098 Ingest Bridge', type: 'Specialized Minor Ingest', reportsReceived: 104, verified: 95, pending: 9, lastIngest: '4m ago', status: 'LIVE FEED', sector: 'Child Welfare Committee' },
      { source: 'Red Cross Mobile Field Units', type: 'Field App Synchronizer', reportsReceived: 184, verified: 152, pending: 32, lastIngest: '8m ago', status: 'STABLE', sector: 'Vidisha & Raisen Belts' },
      { source: 'Citizen Public Portal Web Uploads', type: 'Public Web Portal & WhatsApp', reportsReceived: 168, verified: 112, pending: 56, lastIngest: '12m ago', status: 'LIVE FEED', sector: 'Open Public Gateways' },
      { source: 'NDRF 11th Battalion Rescue Mesh', type: 'Tactical Radio / GPS Telemetry', reportsReceived: 89, verified: 81, pending: 8, lastIngest: '1m ago', status: 'LIVE FEED', sector: 'River Ops Command' },
      { source: 'SDRF Coastal Evacuation Unit', type: 'Field Incident Log API', reportsReceived: 76, verified: 70, pending: 6, lastIngest: '5m ago', status: 'STABLE', sector: 'Lower Basin Watch' },
    ]);

    // 7. Audit Trail Events (Live Ledger)
    console.log('[Seed] Seeding Audit Logs...');
    await AuditLog.insertMany([
      {
        source: 'State Helpline 1070',
        sourceType: 'HELPLINE',
        action: 'Case Registered',
        person: 'Rahul Agrawal',
        caseId: 'MP-2026-00421',
        operator: 'OP-4102',
        status: 'INTAKE',
        details: 'Initial missing report filed with physical description, right chin scar details, and navy blue polo.',
      },
      {
        source: 'Relief Camp Ward 6',
        sourceType: 'RELIEF CAMP',
        action: 'Intake Processed',
        person: 'Rahul Agarwal',
        caseId: 'FND-2026-01892',
        operator: 'NURSE-042',
        status: 'INTAKE',
        details: 'Found individual admitted to relief camp dormitory ward 6.',
      },
      {
        source: 'Automated Biometrics Engine',
        sourceType: 'RELIEF CAMP',
        action: 'Candidate Correlated',
        person: 'Rahul Agrawal',
        caseId: 'MP-2026-00421',
        operator: 'CORR-ENGINE',
        status: 'MATCH',
        details: '94% composite confidence calculated against candidate FND-2026-01892.',
      },
      {
        source: 'Verification Control',
        sourceType: 'RELIEF CAMP',
        action: 'Match Verified',
        person: 'Kavita Yadav',
        caseId: 'MP-2026-00424',
        operator: 'DISP-412',
        status: 'VERIFIED',
        details: 'Field officer confirmed matching gold nose pin and family contact. Reunion recorded.',
      },
      {
        source: 'Childline 1098 Ingest',
        sourceType: 'NGO',
        action: 'Minor Reunited',
        person: 'Master Rohan Gupta',
        caseId: 'MP-2026-00435',
        operator: 'CL-OFFICER-12',
        status: 'VERIFIED',
        details: 'Family verification completed and child transferred to guardian care.',
      },
      {
        source: 'Control Room Dispatch',
        sourceType: 'RELIEF CAMP',
        action: 'Priority Elevated',
        person: 'Aarav Sharma',
        caseId: 'MP-2026-00399',
        operator: 'DISP-884',
        status: 'ALERT',
        details: 'Elevated case priority to CRITICAL due to flash flood watch in Sector S-1.',
      },
    ]);

    console.log('[Seed] Database successfully seeded with 100% comprehensive live data!');
    await mongoose.disconnect();
    process.exit(0);
  } catch (error) {
    console.error('[Seed] Seeding failed:', error);
    process.exit(1);
  }
};

seedData();
